    CREATE TABLE eq_control_conf
(
    ID     int AUTO_INCREMENT COMMENT '自增主键，唯一标识',
    ConfCode   VARCHAR(255)  NOT NULL COMMENT '配置编号，必须唯一',
    ConEquipCode VARCHAR(255) NOT NULL COMMENT '中控设备编号，外键',
    ConsumerRMQUsername   VARCHAR(255)  NOT NULL COMMENT 'ConsumerRMQ username',
    ConsumerRMQPassword   VARCHAR(255)  NOT NULL COMMENT 'ConsumerRMQ password',
    ConsumerRMQHost   VARCHAR(255)  NOT NULL COMMENT 'ConsumerRMQ host',
    ConsumerRMQPort   VARCHAR(255)  NOT NULL COMMENT 'ConsumerRMQ port',
    ConsumerRMQVirtualHost   VARCHAR(255)  NOT NULL COMMENT 'ConsumerRMQ virtual_host',
    ConsumerRMQQueueName  VARCHAR(255)  NOT NULL COMMENT 'ConsumerRMQ queue_name',
    ConsumerRMQBingingKey   VARCHAR(255)  NOT NULL COMMENT 'ConsumerRMQ binging_key',
    ConsumerRMQExchangeName   VARCHAR(255)  NOT NULL COMMENT 'ConsumerRMQ exchange_name',
    ConsumerRMQExchangeType   VARCHAR(255)  NOT NULL COMMENT 'ConsumerRMQ exchange_type',
    ConsumerRMQFailedQueueName   VARCHAR(255)  NOT NULL COMMENT 'ConsumerRMQ failed_queue_name',
    FailedExchangeErrorQueue   VARCHAR(255)  NOT NULL COMMENT 'FailedExchange errorQueue',
    FailedExchangeName  VARCHAR(255)  NOT NULL COMMENT 'FailedExchange name',
    FailedExchangeType   VARCHAR(255)  NOT NULL COMMENT 'FailedExchange type',
    AdvanceAdvance  VARCHAR(255)  NOT NULL COMMENT 'Advance advance',
    AdvancePrefetchCount  VARCHAR(255)  NOT NULL COMMENT 'Advance prefetchCount',
    ConnTimerConnInterval  VARCHAR(255)  NOT NULL COMMENT 'ConnTimer connectInterval',
    ProducerRMQUsername   VARCHAR(255)  NOT NULL COMMENT 'ProducerRabbitMQ username',
    ProducerRMQPassword   VARCHAR(255)  NOT NULL COMMENT 'ProducerRabbitMQ password',
    ProducerRMQHost   VARCHAR(255)  NOT NULL COMMENT 'ProducerRabbitMQ host',
    ProducerRMQPort   VARCHAR(255)  NOT NULL COMMENT 'ProducerRabbitMQ port',
    ProducerRMQVirtualHost   VARCHAR(255)  NOT NULL COMMENT 'ProducerRabbitMQ virtual_host',
    ProducerRMQExchangeName   VARCHAR(255)  NOT NULL COMMENT 'ProducerRabbitMQ exchange_name',
    ProducerRMQExchangeType   VARCHAR(255)  NOT NULL COMMENT 'ProducerRabbitMQ exchange_type',
    ProducerRMQBingingKey   VARCHAR(255)  NOT NULL COMMENT 'ProducerRabbitMQ binging_key',
    ProducerConnTimerConnInterval   VARCHAR(255)  NOT NULL COMMENT 'ProducerConnTimer connectInterval',
    WebRMQUsername varchar(255) NOT NULL COMMENT 'WebRMQUsername',
    WebRMQPassword varchar(255) NOT NULL COMMENT 'WebRMQPassword',
    WebRMQHost varchar(255) NOT NULL COMMENT 'WebRMQHost',
    WebRMQPort varchar(255) NOT NULL COMMENT 'WebRMQPort',
    WebRMQVirtualHost varchar(255) NOT NULL COMMENT 'WebRMQVirtualHost',
    WebRMQExchangeName varchar(255) NOT NULL COMMENT 'WebRMQExchangeName',
    WebRMQExchangeType varchar(255) NOT NULL COMMENT 'WebRMQExchangeType',
    WebRMQBingingKey varchar(255) NOT NULL COMMENT 'WebRMQBingingKey',
    WebRMQQueueName varchar(255) NOT NULL COMMENT 'WebRMQQueueName',
    ConsumerRMQFailedBingingKey varchar(255) NOT NULL COMMENT 'ConsumerRMQFailedBingingKey',
    PRIMARY KEY (ID),
    FOREIGN KEY (ConEquipCode) REFERENCES eq_control (ConEquipCode) ON UPDATE CASCADE ON DELETE CASCADE, -- eq_control ConEquipCode
    UNIQUE (ConfCode)
) COMMENT ='中控设备配置文件表，存储总控设备配置文件的配置项信息，ConfCode唯一';